status = [
  "ci/hydra:Cardano:cardano-prelude:required",
  "ci/x86_64-linux._automation.ciJobs.required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
